version: '3'

services:
  node-app:
    container_name: challenge-app
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    command: npm run development
    depends_on:
      - mysql_db

  mysql_db:
    container_name: mysql_db
    image: mysql:8.1
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sword_challenge_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
