apiVersion: v1
kind: ConfigMap
metadata:
  name: node-app-configmap
data:
  NODE_PORT: '3000'
  MYSQL_HOST: 'mysql'
  MYSQL_PORT: '3306'
  MYSQL_USER: 'root'
  MYSQL_DATABASE: 'sword_challenge_db'
  AMQP_SERVER: 'amqp://root:password@rabbitmq:5672'
  QUEUE_NAME: 'tasks_notifications'
  JWT_SECRET: '4JvBUSVUsSZOw63wV9f35tPLBJ6Wflwf'
  JWT_EXPIRES: '30d'
